feat(dépôt de besoins): Ajout des dépôts de besoins sur Brevo
gip-inclusion/le-marche pull request #1123
Opened 2024-03-11 10:29 UTC by madjid-asa

### Quoi ?

Ajout des dépôts de besoins sur Brevo.

### Pourquoi ?

Permettre un suivi buizdev des dépôts de besoins

### Comment ? 

1. Synchro du DDB
2. Link du DDB avec le contact Brevo

### ⚠️ Reste à faire pour mise en prod opérationnelle

- [ ]  PR synchro des utilisateurs sur brevo pour MAJ de `crm_id`
- [ ]  PR synchro du DDB après validation par l'admin

2024-04-26 09:28 UTC, SebastienReuiller requested changes
Je n'ai pas été jusqu'à testé le webhook.
Juste des petites remarques.

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/www/tenders/tasks.py
> +from lemarche.utils.apis import api_hubspot, api_mailjet, api_n8n, api_slack
Tu as doublé la ligne d'import ;)

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/www/tenders/tasks.py
> +    data_to_send = get_data_to_notify_admin_tender(tender=tender)
Tu as fait une fonction `get_data_to_notify_admin_tender` parce que tu en as besoin ailleurs que dans cette fonction ?

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/utils/apis/api_n8n.py
> +BASE_URL = "https://hooks.slack.com/services/"
Un résidu je pense :)

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/utils/apis/api_n8n.py
> +    """Huey task to send message to specific payload for specific slack service
Le commentaire n'est pas à jour.

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/utils/apis/api_n8n.py
> +    # if settings.SLACK_NOTIF_IS_ACTIVE:
ça parle de Slack.

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/utils/apis/api_n8n.py
> +        response = client.post(f"{webhook_url}", data=data)
Le f-string n'est pas nécessaire a priori.

2024-04-26 09:28 UTC, SebastienReuiller commented on lemarche/utils/apis/api_n8n.py
> +        print("N8N: send data to webhook")
Un petit `print` qui est resté

2024-05-03 09:21 UTC, raphodn approved these changes

2024-05-03 09:21 UTC, raphodn commented on lemarche/tenders/models.py
> +    crm_id = models.CharField("Brevo crm id", max_length=80, validators=[MinLengthValidator(8)], blank=True, null=True)
renommer à `brevo_deal_id` ?

2024-05-03 09:21 UTC, raphodn commented on lemarche/users/models.py
> +    crm_id = models.PositiveIntegerField("Brevo crm id", blank=True, null=True)
renommer à `brevo_contact_id` ?

2024-05-03 10:55 UTC, merged