feat(Dépôt de besoins): renommer les titres d'emails pour ne pas avoir l'impression d'envoyer deux fois le même mail
gip-inclusion/le-marche pull request #1166
Opened 2024-04-19 09:33 UTC by madjid-asa

Renommer les titres d'emails pour ne pas avoir l'impression d'envoyer deux fois le même mail.

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Des demandes de supports concernant les mails en doublons.

### Comment ?

Rendre les titres d'emails plus uniques.

2024-04-22 15:15 UTC, SebastienReuiller requested changes

2024-04-22 16:06 UTC, madjid-asa commented on lemarche/www/tenders/tasks.py
> +    email_subject = f"[Marché de l'inclusion] {tender.get_kind_display()} : {tender.title} "
Hum je comprends mais 20-30 ça fait pas beaucoup non ?

2024-04-24 07:33 UTC, SebastienReuiller commented on lemarche/www/tenders/tasks.py
> +    email_subject = f"[Marché de l'inclusion] {tender.get_kind_display()} : {tender.title} "
Oui, ça ne fait pas beaucoup en effet. On peut mettre 60 ? avec le texte devant ça fera environ 100 caractères, c'est que mon client mail affiche par exemple :)

2024-04-24 16:08 UTC, madjid-asa commented on lemarche/www/tenders/tasks.py
> +    email_subject = f"[Marché de l'inclusion] {tender.get_kind_display()} : {tender.title} "
J'ai choisi l'option de garder que les trois premiers mots du coup : 
- `Appel d'offres : Lot 18 Nettoyage...`

2024-04-26 07:32 UTC, SebastienReuiller approved these changes
LG !

2024-04-29 10:07 UTC, merged