feat: Ajout d'un attribut pour filtrer l'envoi des besoins d'achat
gip-inclusion/le-marche pull request #1446
Opened 2024-09-30 20:47 UTC by chloend

### Quoi ?

Permettre aux admins d’affecter certains dépôts de besoins à des partenaires.

### Pourquoi ?

Des partenaires externes en ont fait la demande.

### Comment ?

- En ajout d'un bouton "Valider et envoyer aux partenaires" dans l'admin des tenders. 

- En ajoutant un attribut 'send_to_commercial_partners_only' dans le modèle Tender qui sera set à True en cliquant sur le bouton "Valider et envoyer aux partenaires". 

- En modifiant la méthode 'validated_sent_batch' de TenderQueryset pour filtrer les envois aux structures lorsque l'attribut est False

### Captures d'écran (optionnel)

Ajout du bouton
![boutons_envoi_besoins](https://github.com/user-attachments/assets/330f5f39-8eec-4681-acae-70488033f702)

Modale avec message personnalisé si structures/partenaires
![confirmation_envoi_structures](https://github.com/user-attachments/assets/58e952bc-252e-4b9c-9bd3-dce5ec1958af)
![confirmation_envoi_partenaires](https://github.com/user-attachments/assets/160a51e3-58d4-41d3-b2be-b5ebfbb83716)

### Tests de l'attribut
- Attribut False par défaut
- Attribut set à True quand on clique sur le bouton adéquat
- L'envoi des besoins par batch skip les besoins dont l'attribut est True

2024-10-01 10:53 UTC, madjid-asa requested changes
Quelques petites modification à apporter mais cool dans l'ensemble :)

2024-10-01 10:53 UTC, madjid-asa commented on lemarche/static/js/admin_tender_confirmation.js
> +            const title = button.getAttribute('data-title');
```suggestion
            const recipient = button.dataset.recipient;
            const title = button.dataset.title;
```
Tu utilise généralement les getAttribute pour les attributs non-standards, mais pour les data-* tu peux utiliser [dataset](https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset)

2024-10-02 08:07 UTC, SebastienReuiller reviewed
Merci @chloend pour ta première PR, elle est top ! J'ai fait une petite remarque sur le message de confirmation pour ma part.
Aussi, à l'usage, je trouve qu'on perd l'info dans l'admin que le dépôt a été envoyé uniquement aux partenaires. Je pense qu'il faut à minima afficher la case à cochée en readonly après la validation ou alors ajouter l'info après le texte "Validé le {{ tender.first_sent_at|date }}" .

2024-10-02 08:07 UTC, SebastienReuiller commented on lemarche/static/js/admin_tender_confirmation.js
> +            messageElement.textContent = "Le besoin « " + title + " » sera envoyé aux partenaires.";
J'aurais peut-être précisé ici: "Le besoin '[titre]' sera envoyé uniquement aux prestataires commerciaux.". Qu'en penses tu ?

2024-10-07 08:59 UTC, madjid-asa approved these changes
Bien joué pour ta première PR 💯 🌮

2024-10-07 10:02 UTC, SebastienReuiller approved these changes
LG ! Bravo !

2024-10-07 10:05 UTC, merged