feat: Ajout d'attributs de contact pour les acheteurs inscrits
gip-inclusion/le-marche pull request #1468
Opened 2024-10-17 11:40 UTC by chloend

### Quoi ?

Ajout de trois attributs lors de la création de contact dans la liste #10 (Acheteurs inscrits) de Brevo : 
- MONTANT_BESOIN_ACHETEUR
- TYPE_BESOIN_ACHETEUR
- TYPE_VERTICALE_ACHETEUR

### Pourquoi ?

Pour segmenter les envois d'email et ne pas multiplier les listes sur Brevo.

### Comment ?

En ajoutant un argument `tender_id` dans la méthode `add_to_contact_list` définie dans emails.py. Cette dernière est appelée dans les trois méthodes de création de Tender (`done`, `perform_create` et `csrf_failure`) afin de récupérer l'id du tender qui permettra d'associer les informations du tender à l'utilisateur de type "acheteur".

### Captures d'écran (optionnel)

![contact_attributs](https://github.com/user-attachments/assets/5c9167eb-c648-4d74-be48-d38cce265788)

### Autre (optionnel)

#### Tests :
- Il manque un test sur la méthode csrf_failure car il était compliqué de récupérer l'erreur csrf dans le test pour la traiter et permettre la création du tender.
- J'ai ajouté un User de type BUYER dans setUpTestData donc j'ai légèrement modifié `test_user_with_valid_api_key_can_create_tender` pour que les assertEqual du nombre de User passent.

2024-10-21 09:00 UTC, SebastienReuiller requested changes

2024-10-21 09:00 UTC, SebastienReuiller commented on lemarche/utils/emails.py
> +            tender_id = user.tenders.first().id if user.tenders.exists() else None
Pourquoi tu ne prends pas le tender_id en paramètre ici ?

2024-10-21 09:00 UTC, SebastienReuiller commented on lemarche/utils/apis/api_brevo.py
> +    from lemarche.tenders.models import Tender
Cet import peut allez en haut ;)

2024-10-21 09:00 UTC, SebastienReuiller commented on lemarche/utils/apis/api_brevo.py
> +            tender = user.tenders.get(id=tender_id)
Bien joué, le petit contrôle de cohérence/sécu ;)

2024-10-24 16:35 UTC, chloend commented on lemarche/utils/apis/api_brevo.py
> +    from lemarche.tenders.models import Tender
Non parce que sinon j'ai un pb d'imports circulaires :o

2024-10-24 16:49 UTC, chloend commented on lemarche/utils/emails.py
> +            tender_id = user.tenders.first().id if user.tenders.exists() else None
Tu veux dire récupérer le tender_id au-dessus du bloc if ?

2024-10-28 10:53 UTC, SebastienReuiller commented on lemarche/utils/apis/api_brevo.py
> +    from lemarche.tenders.models import Tender
Ah, tu peux peut-être t'en sortir avec `from django.core.exceptions import ObjectDoesNotExist` pour éviter l'import ici, si c'est juste pour l'exception.

2024-11-07 09:32 UTC, madjid-asa approved these changes
Juste une petite optimisation de requête à faire mais sinon c'est très bien, bravo :D

2024-11-07 09:32 UTC, madjid-asa commented on lemarche/utils/apis/api_brevo.py
> +        sectors = tender.sectors.all()
```suggestion
```
Pas besoin de cette requête, à la ligne 60, tu peux au lieux du exists, tu check qu'il est pas nul :) 
```suggestion
        first_sector = tender.sectors.first()
```

2024-11-07 09:34 UTC, madjid-asa commented on lemarche/utils/apis/api_brevo.py
> +        attributes["MONTANT_BESOIN_ACHETEUR"] = tender.amount
```suggestion
        attributes["MONTANT_BESOIN_ACHETEUR"] = tender.amount_int
```

2024-11-07 10:09 UTC, chloend commented on lemarche/utils/apis/api_brevo.py
> +            attributes["MONTANT_BESOIN_ACHETEUR"] = tender.amount
ah oui j'avais oublié !

2024-11-07 14:23 UTC, merged