Chloend/migration flatpage wagtail
gip-inclusion/le-marche pull request #1496
Opened 2024-11-05 17:52 UTC by chloend

### Quoi ?

Migration des pages FlatPage vers Wagtail.

### Pourquoi ?

Pour regrouper toutes les pages dans le cms et éviter les confusions entre les modèles Page de FlatPage et Wagtail.

### Comment ?

- En supprimant le dossier 'lemarche/pages' qui comprenait les modèles Page et PageFragment.
- En supprimant les pages inutiles dans 'lemarche/www/pages'.
- En créant une commande de management pour populer le cms de pages statiques telles que 'cgu' ou 'mentions-legales'.
- En créant les anciennes pages FlatPage dans wagtail, en production.

### Autre (optionnel)

- le fichier 'cms_content_pages.json' a été placé dans 'lemarche/fixtures' au lieu de 'lemarche/fixtures/django' parce qu'il sert à la commande `create_content_pages` et ne peut être chargé en tant que fixtures.

2024-11-07 16:32 UTC, madjid-asa requested changes
Je pense que t'as du faire un oubli pour l'ajout du champ dans les pages :)

2024-11-07 16:32 UTC, madjid-asa commented on lemarche/cms/models.py
> +    sub_header_custom_message = StreamField(
Pourquoi t'as ajouté ça ?

2024-11-07 16:32 UTC, madjid-asa commented on lemarche/cms/migrations/0014_homepage_sub_header_custom_message.py
> +from django.db import migrations
Je pense que t'as pas vraiment besoin de ça :)

2024-11-12 11:35 UTC, chloend commented on lemarche/cms/models.py
> +    sub_header_custom_message = StreamField(
C'est pour remplacer l'utilisation du modèle PageFragment dans ArticleBase. Sorry j'ai oublié de préciser, j'avais oublié pourquoi j'avais ajouté ça en vrai héhé

2024-11-13 15:08 UTC, madjid-asa approved these changes
LG 🗡️

2024-11-13 15:08 UTC, madjid-asa commented on lemarche/cms/models.py
> +    sub_header_custom_message = StreamField(
Bien joué ;)

2024-11-13 15:20 UTC, madjid-asa commented on lemarche/cms/models.py
> +    sub_header_custom_message = StreamField(
Le mettre juste en charfield sinon :)

2024-11-13 15:59 UTC, madjid-asa commented
> Nous n'avons plus de page /faq, c'est voulu ?
> 
Elle est identique à la page `Qui sommes nous ?`
> Pour la suppression du module Pages, si on supprime d'un coup, nous allons avoir des tables résiduelles en base de données. Je te propose donc, de le "vider", notamment au niveau des modèles afin de générer les migrations de suppression. Nous pourrons le supprimer totalement dans une autre PR.
Damn j'avais zappé toute les pages qu'il y avait dans ce dossier ^^ 
y a toute ces pages :
![image](https://github.com/user-attachments/assets/9978a68a-2341-445c-8166-f823489e5d28)

dont la méthode csrf qui est assez importante ^^ (malheureusement)

ce que tu peux supprimer c'est le fichier models de page, au niveau des vues c'est HomeView, PageView et c'est tout je crois, et au niveau des urls c'est toutes celles qui sont basées sur HomeView (path("ancien_accueil") et PageView, et toute les statics (de la ligne 36 à 65) :visage_légèrement_souriant:

> Aussi, je n'ai pas compris le sub_header_custom_message 🤔
C'est pour les messages de promotion on les utilisaient à un moment notamment pour les annonces de webinaires

2024-11-13 16:01 UTC, madjid-asa requested changes
> Nous n'avons plus de page /faq, c'est voulu ?
> 
Elle est identique à la page `Qui sommes nous ?`
> Pour la suppression du module Pages, si on supprime d'un coup, nous allons avoir des tables résiduelles en base de données. Je te propose donc, de le "vider", notamment au niveau des modèles afin de générer les migrations de suppression. Nous pourrons le supprimer totalement dans une autre PR.

Damn j'avais zappé toute les pages qu'il y avait dans ce dossier ^^ 
![image](https://github.com/user-attachments/assets/9978a68a-2341-445c-8166-f823489e5d28)

dont la méthode csrf qui est assez importante ^^ (malheureusement)

ce que tu peux supprimer c'est le fichier models de page, au niveau des vues c'est HomeView, PageView et c'est tout je crois, et au niveau des urls c'est toutes celles qui sont basées sur HomeView (path("ancien_accueil") et PageView, et toute les statics (de la ligne 36 à 65) :visage_légèrement_souriant:

> Aussi, je n'ai pas compris le sub_header_custom_message 🤔
C'est pour les messages de promotion on les utilisaient à un moment notamment pour les annonces de webinaires

2024-11-20 17:20 UTC, merged