feat: Ajout d'attributs dans Brevo pour les structures
gip-inclusion/le-marche pull request #1513
Opened 2024-11-11 17:30 UTC by chloend

### Quoi ?

Partie 2 de la synchro Brevo, donc suite de la [PR1468](https://github.com/gip-inclusion/le-marche/pull/1468)
Ajout d'attributs dans la liste des Structures dans Brevo.

### Pourquoi ?

Pour segmenter les envois d’email marketing, et ne pas multiplier les listes sur Brevo.

### Comment ?

En ajoutant 3 attributs dans siae.extra_data :
- siae.completion_rate
- siae.tender_email_send_count_annotated (besoins reçus les 90 derniers jours)
- siae.tender_detail_contact_click_count_annotatedsiae.tender_detail_contact_click_count_annotated (nombre de fois qu'une structure est intéressée par un besoin ces 90 derniers jours)

> Ces deux derniers attributs ne sont pas directement ceux de Siae mais des champs annotés dans un queryset de SiaeQueryset

Enfin, le dictionnaire est initialisé et/ou mis à jour dans la commande `crm_brevo_sync_companies`.

2024-11-20 10:58 UTC, SebastienReuiller requested changes
Des petits retours, essentiellement pour la lisibilité ;)

2024-11-20 10:58 UTC, SebastienReuiller commented on lemarche/siaes/models.py
> +    def with_tender_stats(self, days=0):
Le `days` n'est pas très parlant, que penses-tu d'un truc du genre "retroactive_days" ?
Et je pense qu'il vaut mieux le mettre à None par défaut.

2024-11-20 10:58 UTC, SebastienReuiller commented on lemarche/siaes/models.py
> +                Case(
Alors ici, je pense que tu peux le faire directement sans variable "date_filter" comme tu as fait plus bas.

Aussi, je pense que tu peux faire soit l'un soit l'autre et que tu n'as pas besoin du &, car c'est sur le même champs date et si tu es gte à une date, c'est par null.

```suggestion
                Case(
                    When(
                        (
                            Q(tendersiae__email_send_date__isnull=False)
                            if date_limit is None
                            else Q(tendersiae__email_send_date__gte=date_limit)
                        ),
                        then=1,
                    ),
```

2024-11-20 10:58 UTC, SebastienReuiller commented on lemarche/crm/management/commands/crm_brevo_sync_companies.py
> +        siaes_qs = Siae.objects.with_tender_stats(days=90)
Je pense qu'ici, tu dois continuer avec le même query_set :
```suggestion
        siaes_qs = siaes_qs.with_tender_stats(days=90)
```

2024-11-28 09:33 UTC, SebastienReuiller approved these changes
Top !

2024-11-28 09:33 UTC, SebastienReuiller commented on lemarche/crm/tests.py
> +            "Les clics de contact récents dans les 90 jours devraient être 1",
Trop bien les messages sur les asserts !

2024-12-04 19:02 UTC, madjid-asa requested changes
Je te propose qu'on finalise ça ensemble demain, faudrait ajouter les nouveaux attributs sur brevo et juste les renommer comme il faut et on peut envoyer :)

2024-12-04 19:02 UTC, madjid-asa commented on lemarche/crm/management/commands/crm_brevo_sync_companies.py
> +                siae.extra_data = new_extra_data
extra_data peut contenir d'autres attributs que ceux là, donc en faisant ça t'écrase les anciens attributs ^^ faudrait juste écraser les anciennes clés.

D'ailleurs je pense que les clés ne doivent pas correspondre dans Brevo, faut utiliser une notation de type `TAUX_DE_COMPLETION` sans accents :)

2024-12-04 19:02 UTC, madjid-asa commented on lemarche/siaes/models.py
> +def count_field(field_name, date_limit):
Jolie

2024-12-09 16:04 UTC, madjid-asa commented on lemarche/crm/management/commands/crm_brevo_sync_companies.py
> +            if siae.extra_data != new_extra_data:
```suggestion
            if siae.extra_data.get('brevo_company_data') != new_extra_data:
```

2024-12-09 16:28 UTC, madjid-asa approved these changes
LGTM 🎉

2024-12-09 16:44 UTC, merged