feat(Siae): Permettre aux structures de changer leur nom commercial
gip-inclusion/le-marche pull request #1552
Opened 2024-11-27 16:54 UTC by SebastienReuiller

### Quoi ?

Ajout de l'édition du nom commercial dans le tableau de bord des structures.

### Pourquoi ?

Il y a régulièrement des demandes au support.

### Comment ?

Le champs "brand", récupéré lors de la synchronisation avec les emplois, devient éditable. La synchro le rempli uniquement si il est vide.

Ce champs devient également modifiable par les admins.

### Captures d'écran

#### Le formulaire d'édition

![image](https://github.com/user-attachments/assets/c4fb5651-1c69-41b5-b1f7-e8cb3a04b353)

#### Sur la fiche

Ajout de la raison sociale et corrections des icônes.

Avant

![image](https://github.com/user-attachments/assets/a4121b98-3496-4bf4-9b0e-67d2f612a868)

Après

![image](https://github.com/user-attachments/assets/ae9b44e5-58d0-4160-9305-848913ef2652)

2024-12-02 08:17 UTC, madjid-asa requested changes
Faudrait juste checker le comportement du `update` avec le `clean`.

Peut être que tu peux rajouter un test sur la management command d'import du coup ? là ton test est uniquement basé sur le formulaire d'édition

2024-12-02 08:17 UTC, madjid-asa commented on lemarche/siaes/models.py
> +    def clean(self):
ça ne risque pas de foirer la synchro si on importe un nom qui existe déjà ? 
au pire faudrait gérer ça dans la synchro ? je sais pas le comportement du update sur le clean ?

2024-12-02 09:35 UTC, SebastienReuiller commented on lemarche/siaes/models.py
> +    def clean(self):
Pour moi, l'update passe pas le clean, mais tu as raison, je vais ajouter des tests et gérer le cas côté synchro.

2024-12-04 17:03 UTC, madjid-asa approved these changes
Niice Job :D

2024-12-05 09:10 UTC, chloend approved these changes

2024-12-05 09:52 UTC, merged