feat(Admin des Besoins): Demande de modification ou clôture d'un besoin
gip-inclusion/le-marche pull request #1596
Opened 2024-12-17 10:09 UTC by chloend

### Quoi ?

Permettre 

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

2024-12-19 11:21 UTC, madjid-asa commented on lemarche/tenders/migrations/0097_add_templatetransactional_tender_author_reject_message.py
> +from django.db import migrations
essai de regrouper toute tes modification dans une seul pour simplifier la lecture

2024-12-19 11:21 UTC, madjid-asa commented on lemarche/www/pages/views.py
> +            fields_set = set()
je ne comprend pas pourquoi tu initialise un set() comme ça

2024-12-19 11:21 UTC, madjid-asa commented on lemarche/www/pages/views.py
> +            fields_set = set()
il me semble qu'il ne sert pas à grand chose

2024-12-31 13:31 UTC, Guilouf commented on lemarche/tenders/admin.py
> +        if obj.email_sent_for_modification:
Cette condition est redondante, elle est déjà testée au niveau de l'appel de la fonction, l869

2024-12-31 13:31 UTC, Guilouf commented on lemarche/tenders/management/commands/update_tender_status_to_rejected.py
> +                email_sent_at_date = timezone.now().strptime(email_sent_at, "%Y-%m-%dT%H:%M:%S.%f%z")
Ca dépasse sans doute le scope de cette PR, mais stocker les logs dans un JSON field au lieu d'avoir une relation vers un objet log ajoute beaucoup de difficulté j'ai l'impression.
Sans ca, toute la boucle ici pourrait être simplifié par un `Tender.objects.update(....)`

2024-12-31 13:31 UTC, Guilouf commented on lemarche/tenders/management/commands/update_tender_status_to_rejected.py
> +                email_sent_at_date = timezone.now().strptime(email_sent_at, "%Y-%m-%dT%H:%M:%S.%f%z")
Si j'ai bien compris "email_sent_at" est en format iso, donc on doit pouvoir utiliser `fromisoformat` https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat

2024-12-31 13:31 UTC, Guilouf commented on lemarche/conversations/migrations/0018_add_templatetransactional_tender_author_modification_request_and_reject_message.py
> +    TemplateTransactional.objects.get(code="TENDERS_AUTHOR_MODIFICATION_REQUEST").delete()
Plutot filter que get car si en dev on fait nimp et qu'on supprime le tender en question lors de la reverse on risque d'avoir une erreur

2025-01-02 12:08 UTC, madjid-asa commented on lemarche/tenders/management/commands/update_tender_status_to_rejected.py
> +                email_sent_at_date = timezone.now().strptime(email_sent_at, "%Y-%m-%dT%H:%M:%S.%f%z")
effectivement suite à notre discussion ce matin, je vous propose qu'on se pose sur cette architecture au retour de @SebastienReuiller

2025-01-21 18:05 UTC, SebastienReuiller requested changes
Super fonctionnalité, bravo !
Je t'ai fait quelques retours ;)

2025-01-21 18:05 UTC, SebastienReuiller commented on lemarche/tenders/admin.py
> +        if obj.status == tender_constants.STATUS_REJECTED:
Pour moi, le `status` est à juste titre en lecture seule, donc je ne vois pas comment on peut tomber dans ce cas ? Ta volonté était bien de permettre le rejet depuis l'admin ou uniquement après l'expiration de la demande de modifications ?

2025-01-30 16:52 UTC, Guilouf requested changes
![image](https://github.com/user-attachments/assets/2db8bfda-2697-400b-9ea9-df14b430d787)
Lorsque la demande à été rejetée, elle est toujours listée parmi les demandes de l'acheteur, mais rien n'indique qu'elle a été rejetée. Il faudrait faire pareil quel lorsqu'elle est cloturée, ex:
![image](https://github.com/user-attachments/assets/bc100ce1-b506-46c3-8558-d630caa54971)

2025-02-04 17:06 UTC, SebastienReuiller commented on clevercloud/tenders_update_status_to_rejected.sh
> +django-admin update_tender_status_to_rejected
Oui, j'ai renommé la commande pour le coup, le nom des scripts permet de les "regrouper".

2025-02-05 14:50 UTC, SebastienReuiller commented
J'ai également corrigé le chevauchement sur le lien. Merci @Guilouf pour ta vigilance.

Avant:

![image](https://github.com/user-attachments/assets/3ae7a220-659a-4413-a0e4-c689f91072a3)

Après:

![image](https://github.com/user-attachments/assets/10f8013f-0eb9-4d3c-b885-0b9374655910)

2025-02-06 15:03 UTC, Guilouf commented on lemarche/tenders/constants.py
> +STATUS_REJECTED = "REJECTED"
Il n'y a pas de catégorie "Rejeté" dans la liste des besoins, et par ailleurs avoir "Le besoin n'a pas été encore envoyé" dans un DDB rejeté est peut être trompeur car il ne peut de toutes façon plus être envoyé
![image](https://github.com/user-attachments/assets/988faac7-3f93-4332-955c-78d1fe8d27e9)

2025-02-07 16:41 UTC, SebastienReuiller commented
Nouveau message dans la liste:
![image](https://github.com/user-attachments/assets/9c7cfd0c-e0c6-4626-8fe0-6764c5db08bd)

Onglet et message pour les rejetés:
![image](https://github.com/user-attachments/assets/264cf4fc-98f8-466b-9d04-44610cdce0aa)

2025-02-11 11:05 UTC, Guilouf approved these changes
Ca me parait nickel, merci pour tes corrections !

2025-02-17 09:48 UTC, merged